db_path: data/db.sqlite3
run_every_n_minute: 1
url: https://www.cian.ru/cat.php?bbox=55.7242977705%2C37.5897838344%2C55.7652089417%2C37.7442790736&currency=2&deal_type=rent&engine_version=2&maxprice=65000&metro%5B0%5D=95&metro%5B1%5D=108&metro%5B2%5D=123&minprice=60000&offer_type=flat&room1=1&room9=1&sort=creation_date_desc&type=4
message_template_path: data/message_template.html